# Script path ------------------------------------------------------------------
# Where are script for the pipeline
script_path: 

# Files ------------------------------------------------------------------------
# Fastq of the pure sample
ref: ERR035980_1.fastq.gz
# Directory with all fastq of the pools sample
fastq_dir: ./Fastq/
# Fasta file of your reference
genome: reference.fa
# The final output
output: variant_calling_result.txt

# Config module ----------------------------------------------------------------
# Path source module
src_module: /etc/profile.d/pasteur_modules.sh
# Rules module
mapping_module: "bwa/0.6.2 samtools/1.2"
mutect_module: "muTect/1.1.4"
picard_module: "picard-tools/1.94"

# Pipeline output --------------------------------------------------------------
# If you have a prokka file add inside params.
# params: ["--annotation path/to/file.gbf"]
pipeline_output:
    params: []
